export const enum Categorias {ACEITES, AGUA_BEBIDAS, LEGUMBRES, LACTEOS, DULCES_POSTRES, BODEGA, INFUSIONES,
    CEREALES, CHARCUTERÍA, CONGELADOS, CONSERVAS, HIGIENE, FRUTA_VERDURA, CARNE_HUEVOS, PESCADO_MARISCO,PROFILACTICOS
    ,LIMPIEZA_HOGAR, PANADERIA};
