export const enum Categorias {
  ACEITES = "Aceites",
  AGUA_BEBIDAS = "Agua bebidas",
  LEGUMBRES = "Legumbres",
  LACTEOS = "Lácteos",
  DULCES_POSTRES = "Dulces y postres",
  BODEGA = "Bodega",
  INFUSIONES = "Infusiones",
  CEREALES = "Cereales",
  CHARCUTERIA = "Charcutería",
  CONGELADOS = "Congelados",
  CONSERVAS = "Conservas",
  HIGIENE = "Higiene",
  FRUTA_VERDURA = "Fruta y verdura",
  CARNE_HUEVOS = "Carne y huevos",
  PESCADO_MARISCO = "Pescado y marisco",
  PROFILACTICOS = "Profilácticos",
  LIMPIEZA_HOGAR = "Limpieza del hogar",
  PANADERIA = "Panadería"
};
